/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -o -t -k assets/Protector10.glb Protector10.tsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Cylinder_3: THREE.Mesh;
    Cylinder_4: THREE.Mesh;
    right_engine_cube: THREE.Mesh;
    left_wing: THREE.Mesh;
    right_wing: THREE.Mesh;
    nose_cone: THREE.Mesh;
    RRE_rear_top_1: THREE.Mesh;
    RRE_rear_top_2: THREE.Mesh;
    RRE_rear_top_3: THREE.Mesh;
    RRE_rear_top_4: THREE.Mesh;
    RRE_rear_top_5: THREE.Mesh;
    RRE_rear_top_6: THREE.Mesh;
    RRE_rear_top_7: THREE.Mesh;
    RRE_rear_top_8: THREE.Mesh;
    RRE_rear_bottom_1: THREE.Mesh;
    RRE_rear_bottom_2: THREE.Mesh;
    RRE_rear_bottom_3: THREE.Mesh;
    RRE_rear_bottom_4: THREE.Mesh;
    RRE_rear_bottom_5: THREE.Mesh;
    RRE_rear_bottom_6: THREE.Mesh;
    RRE_rear_bottom_7: THREE.Mesh;
    RRE_rear_bottom_8: THREE.Mesh;
    right_front_engine: THREE.Mesh;
    RFE1_rear: THREE.Mesh;
    RFE_front_1: THREE.Mesh;
    RFE_front_2: THREE.Mesh;
    RFE_front_3: THREE.Mesh;
    RFE_front_4: THREE.Mesh;
    RFE_front_5: THREE.Mesh;
    RFE_front_7: THREE.Mesh;
    RFE_front_8: THREE.Mesh;
    RFE2_rear: THREE.Mesh;
    RFE3_rear: THREE.Mesh;
    RFE4_rear: THREE.Mesh;
    RFE5_rear: THREE.Mesh;
    RFE6_rear: THREE.Mesh;
    RFE7_rear: THREE.Mesh;
    RFE8_rear: THREE.Mesh;
    left_front_engine: THREE.Mesh;
    LFE1_rear001: THREE.Mesh;
    LFE_front_1001: THREE.Mesh;
    LFE_front_2001: THREE.Mesh;
    LFE_front_3001: THREE.Mesh;
    LFE_front_4001: THREE.Mesh;
    LFE_front_5001: THREE.Mesh;
    LFE_front_6001: THREE.Mesh;
    LFE2_rear001: THREE.Mesh;
    LFE3_rear001: THREE.Mesh;
    LFE4_rear001: THREE.Mesh;
    LFE5_rear001: THREE.Mesh;
    LFE6_rear001: THREE.Mesh;
    LFE7_rear001: THREE.Mesh;
    LFE8_rear001: THREE.Mesh;
    LFE_front_7001: THREE.Mesh;
    LFE_front_8001: THREE.Mesh;
    right_engine_cube001: THREE.Mesh;
    LRE_rear_bottom_1: THREE.Mesh;
    LRE_rear_bottom_2: THREE.Mesh;
    LRE_rear_bottom_3: THREE.Mesh;
    LRE_rear_bottom_4: THREE.Mesh;
    LRE_rear_bottom_5: THREE.Mesh;
    LRE_rear_bottom_6: THREE.Mesh;
    LRE_rear_bottom_7: THREE.Mesh;
    LRE_rear_bottom_8: THREE.Mesh;
    LRE_rear_top_1: THREE.Mesh;
    LRE_rear_top_5: THREE.Mesh;
    LRE_rear_top_2: THREE.Mesh;
    LRE_rear_top_3: THREE.Mesh;
    LRE_rear_top_4: THREE.Mesh;
    LRE_rear_top_6: THREE.Mesh;
    LRE_rear_top_7: THREE.Mesh;
    LRE_rear_top_8: THREE.Mesh;
    tail_light: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    blue: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Protector10Public.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="hull"
        position={[-0.01, 0, 0.05]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.27, 2.42, 0.27]}
      >
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Cylinder_1"
          geometry={nodes.Cylinder_1.geometry}
          material={materials.blue}
        />
        <mesh
          name="Cylinder_2"
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          name="Cylinder_3"
          geometry={nodes.Cylinder_3.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          name="Cylinder_4"
          geometry={nodes.Cylinder_4.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        name="right_engine_cube"
        geometry={nodes.right_engine_cube.geometry}
        material={materials["Material.001"]}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="left_wing"
        geometry={nodes.left_wing.geometry}
        material={materials["Material.001"]}
        position={[-0.98, -0.11, 0.06]}
        rotation={[0.18, 1.57, 0]}
        scale={[-0.5, -0.11, -0.33]}
      />
      <mesh
        name="right_wing"
        geometry={nodes.right_wing.geometry}
        material={materials["Material.001"]}
        position={[0.98, -0.01, 0.1]}
        rotation={[-2.96, -Math.PI / 2, 0]}
        scale={[-0.5, -0.11, -0.33]}
      />
      <mesh
        name="nose_cone"
        geometry={nodes.nose_cone.geometry}
        material={nodes.nose_cone.material}
        position={[-0.01, 0.02, -1.65]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.37, 0.7, 0.21]}
      />
      <mesh
        name="RRE_rear_top_1"
        geometry={nodes.RRE_rear_top_1.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_top_2"
        geometry={nodes.RRE_rear_top_2.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_top_3"
        geometry={nodes.RRE_rear_top_3.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_top_4"
        geometry={nodes.RRE_rear_top_4.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_top_5"
        geometry={nodes.RRE_rear_top_5.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_top_6"
        geometry={nodes.RRE_rear_top_6.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_top_7"
        geometry={nodes.RRE_rear_top_7.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_top_8"
        geometry={nodes.RRE_rear_top_8.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_bottom_1"
        geometry={nodes.RRE_rear_bottom_1.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_bottom_2"
        geometry={nodes.RRE_rear_bottom_2.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_bottom_3"
        geometry={nodes.RRE_rear_bottom_3.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_bottom_4"
        geometry={nodes.RRE_rear_bottom_4.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_bottom_5"
        geometry={nodes.RRE_rear_bottom_5.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_bottom_6"
        geometry={nodes.RRE_rear_bottom_6.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_bottom_7"
        geometry={nodes.RRE_rear_bottom_7.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="RRE_rear_bottom_8"
        geometry={nodes.RRE_rear_bottom_8.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="right_front_engine"
        geometry={nodes.right_front_engine.geometry}
        material={materials["Material.001"]}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE1_rear"
        geometry={nodes.RFE1_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE_front_1"
        geometry={nodes.RFE_front_1.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE_front_2"
        geometry={nodes.RFE_front_2.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE_front_3"
        geometry={nodes.RFE_front_3.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE_front_4"
        geometry={nodes.RFE_front_4.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE_front_5"
        geometry={nodes.RFE_front_5.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE_front_7"
        geometry={nodes.RFE_front_7.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE_front_8"
        geometry={nodes.RFE_front_8.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE2_rear"
        geometry={nodes.RFE2_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE3_rear"
        geometry={nodes.RFE3_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE4_rear"
        geometry={nodes.RFE4_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE5_rear"
        geometry={nodes.RFE5_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE6_rear"
        geometry={nodes.RFE6_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE7_rear"
        geometry={nodes.RFE7_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="RFE8_rear"
        geometry={nodes.RFE8_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="left_front_engine"
        geometry={nodes.left_front_engine.geometry}
        material={materials["Material.001"]}
        position={[-0.7, 0.05, 0.2]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE1_rear001"
        geometry={nodes.LFE1_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE_front_1001"
        geometry={nodes.LFE_front_1001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE_front_2001"
        geometry={nodes.LFE_front_2001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE_front_3001"
        geometry={nodes.LFE_front_3001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE_front_4001"
        geometry={nodes.LFE_front_4001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE_front_5001"
        geometry={nodes.LFE_front_5001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE_front_6001"
        geometry={nodes.LFE_front_6001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE2_rear001"
        geometry={nodes.LFE2_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE3_rear001"
        geometry={nodes.LFE3_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE4_rear001"
        geometry={nodes.LFE4_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE5_rear001"
        geometry={nodes.LFE5_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE6_rear001"
        geometry={nodes.LFE6_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE7_rear001"
        geometry={nodes.LFE7_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE8_rear001"
        geometry={nodes.LFE8_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE_front_7001"
        geometry={nodes.LFE_front_7001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="LFE_front_8001"
        geometry={nodes.LFE_front_8001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name="right_engine_cube001"
        geometry={nodes.right_engine_cube001.geometry}
        material={materials["Material.001"]}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_bottom_1"
        geometry={nodes.LRE_rear_bottom_1.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_bottom_2"
        geometry={nodes.LRE_rear_bottom_2.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_bottom_3"
        geometry={nodes.LRE_rear_bottom_3.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_bottom_4"
        geometry={nodes.LRE_rear_bottom_4.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_bottom_5"
        geometry={nodes.LRE_rear_bottom_5.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_bottom_6"
        geometry={nodes.LRE_rear_bottom_6.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_bottom_7"
        geometry={nodes.LRE_rear_bottom_7.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_bottom_8"
        geometry={nodes.LRE_rear_bottom_8.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_top_1"
        geometry={nodes.LRE_rear_top_1.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_top_5"
        geometry={nodes.LRE_rear_top_5.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_top_2"
        geometry={nodes.LRE_rear_top_2.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_top_3"
        geometry={nodes.LRE_rear_top_3.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_top_4"
        geometry={nodes.LRE_rear_top_4.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_top_6"
        geometry={nodes.LRE_rear_top_6.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_top_7"
        geometry={nodes.LRE_rear_top_7.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="LRE_rear_top_8"
        geometry={nodes.LRE_rear_top_8.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name="tail_light"
        geometry={nodes.tail_light.geometry}
        material={materials.Material}
        position={[-0.01, 0, 0.05]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.27, 2.42, 0.27]}
      />
    </group>
  );
}

useGLTF.preload("/Protector10Public.glb");
